### ISSUE TITLE
Compilation fails with GCC 13

### ISSUE THREAD

**Issue by GaetanLepage** [Farama-Foundation/Arcade-Learning-Environment#502]
When trying to install `ale-py` with GCC13 as a compiler, the build fails with several instances of such error:
```
note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
```

I guess that `<cstdint>` has now to be explicitly included: https://gcc.gnu.org/gcc-13/porting_to.html

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for finding that @GaetanLepage, would you be able to submit a PR fixing the issue?

**Comment by GaetanLepage** [comment]
> Thanks for finding that @GaetanLepage, would you be able to submit a PR fixing the issue?

I guess that it would only boil down to adding a bunch of `include <cstdint>` at the beginning of the right files.
However, I fear that I won't have the time for this during the next few days...
