### ISSUE TITLE
pip install ale-py error 

### ISSUE THREAD

**Issue by logu1989** [Farama-Foundation/Arcade-Learning-Environment#505]
I am trying to install ale-py by using pip install ale-py command and get below error.

$pip install ale-py
ERROR: Could not find a version that satisfies the requirement ale-py (from versions: none)
ERROR: No matching distribution found for ale-py

I have also tried upgrading pip.
$pip install --upgrade pip
Requirement already satisfied: pip in c:\users\logan\appdata\local\programs\python\python312\lib\site-packages (23.3.2)

OS: Windows 11
Python Version: Python 3.12.1

**Comment by pseudo-rnd-thoughts** [comment]
Ale-py doesn't have python 3.12 support currently

**Comment by tobiaswuerth** [comment]
Is there a timeline for python 3.12 support?

**Comment by pseudo-rnd-thoughts** [comment]
v0.9.0, hopefully in the next few days
