### ISSUE TITLE
ROM file "Breakout" not found.

### ISSUE THREAD

**Issue by shengdongxue123** [Farama-Foundation/Arcade-Learning-Environment#536]
I am running your example program, but get this bug tips:A.L.E: 
ROM file "Breakout" not found.
How can I solve it?

**Comment by pseudo-rnd-thoughts** [comment]
Could you provide some minimal example to reproduce this. 
What modules have you installed?

**Comment by shengdongxue123** [comment]
win10
py3.8.0
ale_py0.8.1
I have changed your example and run scuccessfully. However, I can't find the reason of the last error.
from ale_py import ALEInterface
from ale_py.roms import AirRaid as game
import random
import cv2

ale = ALEInterface()
ale.loadROM(game)
ale.reset_game()

for i in range(10000):
    # reward = ale.act(random.randint(0, 6))  # noop
    ale.act(i % 6)
    screen_obs = ale.getScreenRGB()
    cv2.imshow('RGB Image', screen_obs)
    cv2.waitKey(1)
    # cv2.destroyAllWindows()
    print(screen_obs)

**Comment by pseudo-rnd-thoughts** [comment]
What is the last error?

**Comment by shengdongxue123** [comment]
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.3 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.12.3
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
from ale_py import ALEInterface
ale = ALEInterface()
ale.loadROM("Breakout")
ale.reset_game()
reward = ale.act(0)  # noop
screen_obs = ale.getScreenRGB()
I run the example program in the readme, but get below information.
A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]
ROM file "Breakout" not found.

**Comment by pseudo-rnd-thoughts** [comment]
I believe you need to use `from ale_py.roms import Breakout` and `ale.loadROM(Breakout)`
