### ISSUE TITLE
ROM file not found on `ale_py 0.9.0`. Should the docs example be changed?

### ISSUE THREAD

**Issue by floringogianu** [Farama-Foundation/Arcade-Learning-Environment#538]
Installed `ale_py` with `pip install ale_py` in a conda environment. The following snippet crashes with `ROM file XXX not found` for any game:

```python
from ale_py import ALEInterface

ale = ALEInterface()
ale.loadROM("Pong")
```

What works instead is importing `roms` and using the `get_rom_path` utility:

```python
from ale_py import ALEInterface, roms

ale = ALEInterface()
ale.loadROM(roms.get_rom_path("pong"))
```

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the issue, @jjshoots is there a nice solution to this where we don't need to change the example?

**Comment by jjshoots** [comment]
Interesting... I think during the past update, we moved the location where all the roms were to another place, and an underlying binding didn't get the memo. I think it wouldn't be too hard to fix the C API. I can get to it tomorrow.

**Comment by pseudo-rnd-thoughts** [comment]
@jjshoots or @floringogianu Could you make a PR to update the documentation

**Comment by jjshoots** [comment]
Sure.
