### ISSUE TITLE
Where exactly to identify the code for the rewards?

### ISSUE THREAD

**Issue by KKamaleshKumar** [Farama-Foundation/Arcade-Learning-Environment#541]
Hi,

I am interested in making a custom reward function that replaces the default reward used. I was looking to find that, so I can use my custom reward and pass the gymnasium env to say sb3. In classic control environments, I used to change the step method where the reward is computed, but was not able to find that in gym for Atari. Looking forward to some help!!

Thanks,

**Comment by pseudo-rnd-thoughts** [comment]
The environments are encoded within the game's rom therefore you can't change the reward function like CartPole.
One approach I have taken is to investigate the rom's ram data or to understand the reward output to indicate what happened
